name: tts_framework
channels:
  - defaults
  - nvidia
  - anaconda
  - conda-forge
  - pytorch-nightly
dependencies:
  - fastapi=0.105.0
  - nltk==3.8.1
  - pytorch-cuda=12.1
  - pytorch=2.4.0
  - torchvision=0.18.0
  - torchaudio=2.2.0
  - lightning=2.2.1
  - libpng=1.6.39
  - ipykernel=6.25.0
  - mkdocs-material=9.4.6
  - mkdocs-material-extensions=1.3
  - mkdocstrings=0.23.0
  - mypy=1.5.1
  - pyright=1.1.331
  - numba=0.58.1
  - pip=23.3
  - numpy=1.25.2
  - scikit-learn=1.2.2
  - tqdm=4.65.0
  - pynini=2.1.5
  - pip:
      - librosa==0.10.0
      - lightning-app==2.2.1
      - lightning-api-access==0.0.5 
      - torchmetrics==1.3.1
      - git+https://github.com/detly/gammatone.git
      - git+https://github.com/NVIDIA/NeMo.git@main#egg=nemo_toolkit[all]
      - auraloss==0.4.0
      - pystoi==0.4.1
      - pesq==0.0.4
      - datasets==2.14.5
      - deep-phonemizer==0.0.19
      - phonemizer==3.2.1
      - resemblyzer==0.1.4
      - nemo-text-processing==0.2.0rc0
      - piq==0.8.0
      - soundfile==0.12.1
      - transformers==4.34.0
      - accelerate==0.25.0
      - einops==0.7.0
      - unidecode==1.3.7
      - ruff==0.1.0
      - mkdocstrings-python==1.7.3
      - tensorboard==2.15.0
      - ipywidgets==8.1.1
      - itables==1.6.3
      - uvicorn==0.24.0
      - ffmpeg==1.4
      - pydub==0.25.1
      - simpleaudio==1.0.4
      - onnx==1.15.0
      - neural-compressor==2.4.1
      - voicefixer==0.1.3
      - vocos==0.1.0
